version: "3.8"

services:
  backend:
    build: .
    container_name: fastapi-backend
    restart: always
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
